### ISSUE TITLE
Divergence between docs and behavior for "replace" parameter

### ISSUE THREAD

**Issue by gwhitney** [athackst/mkdocs-simple-plugin#136]
As of mkdocs 0.5.0, the documentation at https://allisonthackston.com/mkdocs-simple-plugin/mkdocs_simple_plugin/plugin/
states with respect to the "replace" parameter that "If none [of the replace patterns] match, the line is transcribed unchanged." However the code now has the behavior that if the "replace" parameter is specified and none of the patterns match, the line is dropped.

I would be happy to file a pull request to align the two, but would need direction as to whether the documentation should be changed to reflect the changed behavior, or the behavior should be restored to match the documentation.

**Comment by gwhitney** [comment]
Oh, and per a comment you made on some other issue a while back, I will also add a test verifying whichever behavior you deem to be the desired/official one going forward.

**Comment by athackst** [comment]
I think there's a bit of a conflict between the original way `replace` was implemented and what I was trying to use it for, which is more like a "match".

I'll open a PR that returns the `replace` parameter back to transcribing and adds a `match` parameter that drops lines that don't match the regex pattern.

**Comment by gwhitney** [comment]
Just want to point out that technically there is no need to add such a `match` parameter: currently a replace regex that has no associated expansion and no group drops all the lines it matches. And regular expressions are closed under complementation, so you can always find another regular expression that matches exactly the lines that a given regexp doesn't match. So for example if you want to drop all lines that don't start with optional whitespace and then a hash, i.e. whose first non-whitespace character is not a hash, just use `'^\s*[^#\s]'` as a replace regexp.

**Comment by athackst** [comment]
Sure, but `(.*)` is easier than that, so it seems like inclusion-based is an easier pattern.

If you just want to update the docs, I think that sounds good too.

**Comment by gwhitney** [comment]
OK, if that's the case, then is it OK if a pattern with no group and no associated expansion that matches causes the line to be transcribed unchanged? Since nothing matching now causes the line to be dropped, whereas before that's what would cause the line to be transcribed unchanged?  Thanks for letting me know, happy to resolve this once I hear back.

**Comment by athackst** [comment]
Looking back over, it looks like the real issue was that I didn't correctly port dropping lines in my refactor.

Returned to original implementation and updated the defaults for comment lines to drop non-commented lines.
