### ISSUE TITLE
Infinite reload loop in version 2.2.0

### ISSUE THREAD

**Issue by nickodell** [athackst/mkdocs-simple-plugin#483]
Hello,

Firstly, I would like to express my gratitude for the time and effort you have put into maintaining this package. I am writing to report an issue that I've run into. I have spent some time looking into this and believe that it may be a bug. However, I'm not sure, and I apologize in advance if this is user error. :)

# Summary

I've been running into an issue in mkdocs-simple-plugin, but only in version 2.2.0, and not in 2.1.3.

Essentially, when you edit a file, mkdocs rebuilds the documentation, and it detects the rebuild as a change, and rebuilds again. This continues forever. Here's a log of what happens:

```
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  mkdocs-simple-plugin: build_docs_dir: /tmp/mkdocs_simple_oz5xedz_
INFO     -  mkdocs-simple-plugin: /tmp/tmp.eRaappbCCQ/docs/.gitkeep/* --> /tmp/mkdocs_simple_oz5xedz_/.gitkeep/*
INFO     -  mkdocs-simple-plugin: .mkdocsignore --> /tmp/mkdocs_simple_oz5xedz_/.mkdocsignore
INFO     -  mkdocs-simple-plugin: README.md --> /tmp/mkdocs_simple_oz5xedz_/README.md
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.07 seconds
INFO     -  [17:50:11] Watching paths for changes: '/tmp/mkdocs_simple_oz5xedz_', 'mkdocs.yml', 'docs', '.mkdocsignore', 'README.md'
INFO     -  [17:50:11] Serving on http://127.0.0.1:8000/
< ---- Changed a file here
INFO     -  [17:50:14] Detected file changes
INFO     -  Building documentation...
INFO     -  mkdocs-simple-plugin: build_docs_dir: /tmp/mkdocs_simple_oz5xedz_
INFO     -  mkdocs-simple-plugin: /tmp/tmp.eRaappbCCQ/docs/.gitkeep/* --> /tmp/mkdocs_simple_oz5xedz_/.gitkeep/*
INFO     -  mkdocs-simple-plugin: .mkdocsignore --> /tmp/mkdocs_simple_oz5xedz_/.mkdocsignore
INFO     -  mkdocs-simple-plugin: README.md --> /tmp/mkdocs_simple_oz5xedz_/README.md
INFO     -  [17:50:14] Reloading browsers
INFO     -  [17:50:15] Detected file changes
INFO     -  Building documentation...
INFO     -  mkdocs-simple-plugin: build_docs_dir: /tmp/mkdocs_simple_oz5xedz_
INFO     -  mkdocs-simple-plugin: /tmp/tmp.eRaappbCCQ/docs/.gitkeep/* --> /tmp/mkdocs_simple_oz5xedz_/.gitkeep/*
INFO     -  mkdocs-simple-plugin: .mkdocsignore --> /tmp/mkdocs_simple_oz5xedz_/.mkdocsignore
INFO     -  mkdocs-simple-plugin: README.md --> /tmp/mkdocs_simple_oz5xedz_/README.md
INFO     -  [17:50:15] Reloading browsers
INFO     -  [17:50:15] Detected file changes
INFO     -  Building documentation...
INFO     -  mkdocs-simple-plugin: build_docs_dir: /tmp/mkdocs_simple_oz5xedz_
INFO     -  mkdocs-simple-plugin: /tmp/tmp.eRaappbCCQ/docs/.gitkeep/* --> /tmp/mkdocs_simple_oz5xedz_/.gitkeep/*
INFO     -  mkdocs-simple-plugin: .mkdocsignore --> /tmp/mkdocs_simple_oz5xedz_/.mkdocsignore
INFO     -  mkdocs-simple-plugin: README.md --> /tmp/mkdocs_simple_oz5xedz_/README.md
INFO     -  [17:50:15] Reloading browsers
INFO     -  [17:50:16] Detected file changes
INFO     -  Building documentation...
```

# Debugging info

## mkdocs.yml

I've reduced my config file down to the minimum which still triggers the problem.

```yml
site_name: site

plugins:
  - simple
```

## Versions

- mkdocs: 1.4.2
- mkdocs-simple-plugin: 2.1.3 (working) 2.2.0 (not working)
- Python: 3.10.6
- OS: So far I have reproduced this problem on Ubuntu 22.04 and OSX.

# Full reproduction case

I've made a repo with the above configuration, and a shell script which triggers the error. https://github.com/nickodell/mkdocs-inf-reload-reproducer

If I run it like this, it reloads once after the README file is changed.

```
./repro.sh 2.1.3
```

If I run it like this, after the script changes the README, it loops forever.

```
./repro.sh 2.2.0
```

# Bisection

Bisecting the history between 2.1.3 and 2.2.0 finds that commit 40415a3d913134b5e47312f780a3353364b7fded seems to the the commit which introduces this issue.

**Comment by athackst** [comment]
Thanks for the detailed issue!

I was able to reproduce and will be looking into it

**Comment by athackst** [comment]
I was able to find the issue, I will push it into the next release.

**Comment by nickodell** [comment]
I've tested on the repository which originally had this problem, and I can confirm the fix works. Thanks for the speedy fix!
