### ISSUE TITLE
Demonstrate usage in this site

### ISSUE THREAD

**Issue by flywire** [athackst/mkdocs-simple-plugin#77]
Seems incredible to use a conventional mkdocs layout with such a simple site rather than demonstrating the plugin. A GitHub wiki is also a good example of a site that is too simple for [won't actually allow] a `docs` directory.

**Comment by athackst** [comment]
I don't quite understand what you're suggesting here.  You dislike the theme?

This plugin uses itself to create the documentation site.  I also use it in a variety of other repositories like https://github.com/athackst/dockerfiles which has neither a `mkdocs.yml` nor a `docs` directory.  Rather, the [site](http://athackst.github.io/dockerfiles) is created from the action.

**Comment by flywire** [comment]
Sorry, I appologise. My first impression was the `mkdocs.yml` at the root level with doc files in `mkdocs_simple_plugin`. Apparently not:

```
nav:
- About: README.md
- Mkdocs Simple Generator: mkdocs_simple_plugin/generator.md
- Mkdocs Simple Plugin: mkdocs_simple_plugin/plugin.md
- Github Action: action.md
- Docker: docker/docker.md
- Developers:
  - Developing: mkdocs_simple_plugin/README.md
  - Contributing Guide: CONTRIBUTING.md
```

I still think a GitHub wiki would be a good usage example.
